stages:
  - build
  - test
  - Static Analysis

Job_build:
  stage: build
  image: python:3.8

  script:
    - python3 -V
    - pip3 --version
    - pip3 install -U pip setuptools wheel
    - pip3 install -r requirements_vm.txt


Job_unittest:
  stage: test
  image: python:3.8

  script:
    - python3 -m unittest tests/*.py -v
  

Job_coverage:

  stage: test
  image: python:3.8
  script:
      - pip3 install pytest-cov
      - pytest --cov=kami/ tests/*.py

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


Job_pylint:
  stage: Static Analysis
  image: python:3.8
  allow_failure: true

  script:
    - pylint --disable=all kami
    
