stages:
  - build
  - test
  - Static Analysis

Job_build:
  stage: build
  image: python:3.8

  script:
    - python3 -V
    - pip3 --version
    - pip3 install -r requirements.txt


Job_pytest:
  stage: test
  image: python:3.8

  script:
    - pytest kami
  

Job_coverage:

  stage: test
  image: python:3.8
  script:
      - pip3 install pytest pytest-cov
      - pytest --cov=kami/ tests/*.py
      - coverage report -m
      - coverage-badge

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


Job_pylint:
  stage: Static Analysis
  image: python:3.8
  allow_failure: true

  script:
    - pylint --disable=all kami
