default:
  image: python:3.5.2


stages:
  - build
  - test
  - Static Analysis

Job_build:
  stage: build
  image: python:3.5.2
  script:
    - apt-get update -q -y
    - apt-get install -y python-pip
    - python -V
    - pip3 install -r requirements.txt


Job_pytest:
  stage: test
  image: python:3.5.2
  script:
    - pytest

pylint:
  stage: Static Analysis
  image: python:3.5.2
  script:
    - pylint kami/metrics/*.py
    - pylint kami/parser/*.py
    - pylint kami/kamutils/*.py
