default:
  image: python:3.5.2



stages:
  - build
  - test
  - Static Analysis

Job_build:
  stage: build
  image: python:3.5.2

  script:
    - python --version
    - pip install -r requirements.txt


Job_pytest:
  stage: test
  image: python:3.5.2

  script:
    - pytest

pylint:
  stage: Static Analysis
  image: python:3.5.2

  script:
    - pylint kami/metrics/*.py
    - pylint kami/parser/*.py
    - pylint kami/kamutils/*.py
