stages:
  - build
  - test
  - Static Analysis

Job_build:
  stage: build
  image: python:3.8

  script:
    - sudo apt-get update -q -y
    - sudo apt-get install -y python-pip
    - python -V
    - pip install -r requirements.txt


Job_pytest:
  stage: test
  image: python:3.8

  script:
    - pytest

pylint:
  stage: Static Analysis
  image: python:3.8

  script:
    - pylint kami/metrics/*.py
    - pylint kami/parser/*.py
    - pylint kami/kamutils/*.py
