name: KaMI-lib CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ['3.9', '3.8']
        os: [ubuntu-latest]
    name: Python ${{ matrix.python-version }} - ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements_dev.txt; fi
    - run: |
          find ./kami/ -name '*.py' -exec pylint --rcfile=./.pylintrc {} \;
    - run: |
          pytest ./tests/*.py -p no:warnings